// ROS 2 Humble common_interfaces 等の主要メッセージ型カタログ（型検索用）

const CATALOG: Record<string, string[]> = {
  std_msgs: [
    "Bool",
    "Byte",
    "ByteMultiArray",
    "Char",
    "ColorRGBA",
    "Empty",
    "Float32",
    "Float32MultiArray",
    "Float64",
    "Float64MultiArray",
    "Header",
    "Int8",
    "Int8MultiArray",
    "Int16",
    "Int16MultiArray",
    "Int32",
    "Int32MultiArray",
    "Int64",
    "Int64MultiArray",
    "MultiArrayDimension",
    "MultiArrayLayout",
    "String",
    "UInt8",
    "UInt8MultiArray",
    "UInt16",
    "UInt16MultiArray",
    "UInt32",
    "UInt32MultiArray",
    "UInt64",
    "UInt64MultiArray",
  ],
  geometry_msgs: [
    "Accel",
    "AccelStamped",
    "AccelWithCovariance",
    "AccelWithCovarianceStamped",
    "Inertia",
    "InertiaStamped",
    "Point",
    "Point32",
    "PointStamped",
    "Polygon",
    "PolygonStamped",
    "Pose",
    "Pose2D",
    "PoseArray",
    "PoseStamped",
    "PoseWithCovariance",
    "PoseWithCovarianceStamped",
    "Quaternion",
    "QuaternionStamped",
    "Transform",
    "TransformStamped",
    "Twist",
    "TwistStamped",
    "TwistWithCovariance",
    "TwistWithCovarianceStamped",
    "Vector3",
    "Vector3Stamped",
    "Wrench",
    "WrenchStamped",
  ],
  sensor_msgs: [
    "BatteryState",
    "CameraInfo",
    "ChannelFloat32",
    "CompressedImage",
    "FluidPressure",
    "Illuminance",
    "Image",
    "Imu",
    "JointState",
    "Joy",
    "JoyFeedback",
    "JoyFeedbackArray",
    "LaserEcho",
    "LaserScan",
    "MagneticField",
    "MultiDOFJointState",
    "MultiEchoLaserScan",
    "NavSatFix",
    "NavSatStatus",
    "PointCloud",
    "PointCloud2",
    "PointField",
    "Range",
    "RegionOfInterest",
    "RelativeHumidity",
    "Temperature",
    "TimeReference",
  ],
  nav_msgs: ["GridCells", "MapMetaData", "OccupancyGrid", "Odometry", "Path"],
  builtin_interfaces: ["Time", "Duration"],
  diagnostic_msgs: ["DiagnosticArray", "DiagnosticStatus", "KeyValue"],
  trajectory_msgs: [
    "JointTrajectory",
    "JointTrajectoryPoint",
    "MultiDOFJointTrajectory",
    "MultiDOFJointTrajectoryPoint",
  ],
  shape_msgs: ["Mesh", "MeshTriangle", "Plane", "SolidPrimitive"],
  stereo_msgs: ["DisparityImage"],
  visualization_msgs: ["ImageMarker", "Marker", "MarkerArray", "MenuEntry"],
};

/** `pkg/Type` 形式の全カタログ（パッケージ順・型名順） */
export const ROS_TYPE_CATALOG: readonly string[] = Object.entries(
  CATALOG,
).flatMap(([pkg, types]) => types.map((t) => `${pkg}/${t}`));
